language: r
warnings_are_errors: true
sudo: required
env:
  matrix:
    secure: vHFck/SqO8fbmBW/D8bOi3Q/rWzhquhW8hstki0msFz0m1gLkiZYbmV5Hho3O169g9bKR8q/LLkIYKJbCrMWJpph1oQ2mir+ZupNLHwqkLGrZh9CMHj6B2DiYcm6RXQvKff98mYQrougYYWI9N+LCcRus154zKA1OCvx2rH6JCqj/zbGR6qGv8Wee3JApwj9g0YcbZzt4Hx+39b1urUqcrpZKm7iRnmZCRwZ5CZQu0jh2UoR8Y678wYQX2Ml02bAlKgGOLwflHvlawKpCnXACosQoRSGvO3uOotKUJOqkUpM/33IDH/NS88VnUGL+TK4uhokrkkBtCq8Ysticc/7XglodmC1X6ElQXthPWHHBp/X2qJFM2OawSYC8rN4ZwHN3kFttlWVSGY4wnK8gtI4KaNt6X2klcjner1NWMcb4jO28pgqYnill+58wulihpP3CWQPaJ6dWizbXSckP/s+RIuCvtUIKlijdwU0ZgYRqzzIGQ30YAzF3UdqMhRpsyOviKvgdwXdRGGaSr7+qLdJdH/gbdmLIenJJ8n1po6BZgF3v70lLMo1I8wj4BrG2wiI9yE7LzFotjlcg+c6quQe+vfR5kKQMob140cS50gopuTbEt7UEnW6tAeZRUNoLOphBPwU4nk/f4D4jCAubrZ/OVDllbd3CXhs2uzt0J1+MJg=
